// src/Desktop/Desktop.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import Dock from '__/Dock/Dock.svelte';
  import { theme } from '__/stores/theme.store';
  import '../css/global.scss';
  import ContextMenu from './ContextMenu.svelte';

  const DarkBackground = '/assets/wallpapers/37-1.jpg';
  const LightBackground = '/assets/wallpapers/37-2.jpg';

  let mainEl: HTMLElement;

  $: wallpaperName = $theme === 'dark' ? DarkBackground : LightBackground;

  function preloadImage(path: string) {
    const img = new Image();
    img.src = path;
  }

  onMount(() => {
    preloadImage(LightBackground);
    preloadImage(DarkBackground);
  });
</script>

<main bind:this={mainEl}>
  <ContextMenu targetElement={mainEl} />
  <div />
  <div />
  <Dock />
</main>

<div class="backgroundCover" style="background-image: url({wallpaperName});" />

<style lang="scss">
  main {
    height: 100%;
    width: 100%;

    display: grid;
    grid-template-rows: auto 1fr auto;
  }

  .backgroundCover {
    height: 100%;
    width: 100%;

    z-index: -1;
    position: fixed;
    top: 0;
    left: 0;

    will-change: background-image;

    background-repeat: no-repeat;
    background-size: cover;
    background-position: center;
  }
</style>

// src/views/desktop/Desktop.tsx
import { useEffect, useRef, useState } from 'preact/hooks';
import { ContextMenu } from '__/components/Desktop/ContextMenu/ContextMenu';
import { StartupChime } from '__/components/Desktop/StartupChime';
import { WindowsArea } from '__/components/Desktop/Window/WindowsArea';
import { Dock } from '__/components/dock/Dock';
import { TopBar } from '__/components/topbar/TopBar';
import { LockScreen } from '../../components/LockScreen';
import css from './Desktop.module.scss';

const DarkBackground = '/assets/wallpapers/3-1.jpg';
const LightBackground = '/assets/wallpapers/3-2.jpg';

export const Desktop = () => {
  const outerRef = useRef<HTMLDivElement>();
  const [locked, setLocked] = useState(true);

  useEffect(() => {
    preloadImage(DarkBackground);
    preloadImage(LightBackground);
  }, []);

  if (locked) {
    return <LockScreen onUnlock={() => setLocked(false)} />;
  }

  return (
    <>
      <main ref={outerRef} class={css.main}>
        <ContextMenu outerRef={outerRef} />
        <TopBar />
        <WindowsArea />
        <Dock />
      </main>

      <StartupChime />

      <div class={css.backgroundCover} aria-hidden="true" />
    </>
  );
};

function preloadImage(path: string) {
  const img = new Image();
  img.src = path;
}
