// src/components/apps/Calendar/MonthView.svelte
<script lang="ts">
  import { theme } from '__/stores/theme.store';

  import { DAYS_OF_THE_WEEK } from './calendar-constants';
  import { getDisplayDays } from './calendar-utils';

  export let selectedDate: Date;

  const today = new Date();

  function isToday(date: number, isThisMonth: boolean) {
    return (
      selectedDate.getFullYear() === today.getFullYear() &&
      isThisMonth &&
      selectedDate.getMonth() === today.getMonth() &&
      date === today.getDate()
    );
  }

  $: ({ daysInPrevMonth, daysInThisMonth, daysInNextMonth } = getDisplayDays(selectedDate));
</script>

<div class="container" class:dark={$theme === 'dark'}>
  {#each DAYS_OF_THE_WEEK as day, i}
    <div class="weekday" class:weekend={[5, 6].includes(i)}>{day}</div>
  {/each}

  {#each daysInPrevMonth as date (date)}
    <div class="day" class:today={isToday(date, false)}>
      <div class="date-number" class:this-month={false}>{date}</div>
    </div>
  {/each}

  {#each daysInThisMonth as date (date)}
    <div class="day" class:today={isToday(date, true)}>
      <div class="date-number" class:this-month={true}>{date}</div>
    </div>
  {/each}

  {#each daysInNextMonth as date (date)}
    <div class="day" class:today={isToday(date, false)}>
      <div class="date-number" class:this-month={false}>{date}</div>
    </div>
  {/each}
</div>

<style lang="scss">
  .container {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    grid-template-rows: 30px repeat(6, 1fr);

    flex-grow: 1;

    font-size: 0.95rem;

    > div {
      padding: 0.5rem;
      text-align: right;
    }
  }

  .container.dark .day {
    &:nth-child(7n),
    &:nth-child(7n-1) {
      --bgcolor: #212121;
      --color: #eee;
    }
  }

  .day {
    border: 1px solid #e6e5e6;
    border-top: none;

    display: flex;
    justify-content: flex-end;

    &:nth-child(1n) {
      border-left: none;
    }

    &:nth-child(7n) {
      border-right: none;
    }
    &:nth-child(n + 43) {
      border-bottom: none;
    }

    &:nth-child(7n),
    &:nth-child(7n-1) {
      --bgcolor: var(--app-color-grey-100);
      --color: var(--app-color-dark);

      background-color: var(--bgcolor) !important;
      color: var(--color);
    }

    .date-number {
      --size: 1.5rem;

      height: var(--size);
      width: var(--size);

      line-height: var(--size);
      text-align: center;

      border-radius: 50%;

      display: flex;
      justify-content: center;
      align-items: center;

      color: var(--app-color-grey-500);
    }

    .this-month {
      color: var(--app-color-dark);

      :global(body.dark) & {
        color: var(--app-color-dark);
      }
    }

    &.today {
      .date-number {
        color: #fff;
        background-color: #ec4d3c;

        --size: 1.7rem;
      }
    }
  }

  .weekday,
  .weekend {
    border-bottom: 1.5px solid #c7c7cc;
  }

  .weekend {
    color: #808080;
  }
</style>

// src/components/apps/Calendar/Views/MonthView.tsx
import clsx from 'clsx';
import { useAtom } from 'jotai';
import { calendarAppStore } from '__/stores/calendar.app.store';
import { getDisplayDays } from '../calendar-utils';
import { DAYS_OF_THE_WEEK } from '../constants';
import css from './MonthView.module.scss';

export const MonthView = () => {
  const [selectedDate] = useAtom(calendarAppStore);
  const today = new Date();

  const { daysInPrevMonth, daysInThisMonth, daysInNextMonth } = getDisplayDays(selectedDate);

  /**
   * Render each day block
   * @param daysInMonth the number array of days in the month to be displayed
   * @param isThisMonth flag to check if this day block belongs to current month
   */
  const renderDay = (daysInMonth: number[], isThisMonth: boolean) => {
    return daysInMonth.map((d, i) => {
      const isToday =
        selectedDate.getFullYear() === today.getFullYear() &&
        isThisMonth &&
        selectedDate.getMonth() === today.getMonth() &&
        d === today.getDate();

      return (
        <div
          className={clsx({
            [css.day]: true,
            [css.today]: isToday,
            // [css.selected]: isSelected,
          })}
          key={`day-${i}-${d}-${selectedDate.getMonth()}`}
        >
          <div className={clsx({ [css.dateNumber]: true, [css.thisMonth]: isThisMonth })}>{d}</div>
        </div>
      );
    });
  };

  return (
    <div className={css.monthView}>
      {DAYS_OF_THE_WEEK.map((day, i) => (
        <div className={[5, 6].includes(i) ? css.weekend : css.weekday}>{day}</div>
      ))}
      {renderDay(daysInPrevMonth, false)}
      {renderDay(daysInThisMonth, true)}
      {renderDay(daysInNextMonth, false)}
    </div>
  );
};

export default MonthView;
