// src/components/apps/AppNexus.svelte
<script lang="ts">
  import type { AppID } from '__/stores/apps.store';

  export let appID: AppID;
  export let isBeingDragged: boolean;
</script>

{#if appID === 'calendar'}
  {#await import('__/components/apps/Calendar/Calendar.svelte') then { default: Calendar }}
    <Calendar />
  {/await}
{:else if appID === 'vscode'}
  {#await import('__/components/apps/VSCode/VSCode.svelte') then { default: VSCode }}
    <VSCode {isBeingDragged} />
  {/await}
{:else if appID === 'calculator'}
  {#await import('__/components/apps/Calculator/Calculator.svelte') then { default: Calculator }}
    <Calculator />
  {/await}
{:else}
  {#await import('__/components/apps/Placeholder/Placeholder.svelte') then { default: Placeholder }}
    <Placeholder {appID} />
  {/await}
{/if}

// src/components/apps/AppNexus.tsx
import { AppID } from '__/stores/apps.store';
import { lazy } from 'react';

type AppNexusProps = {
  appID: AppID;
  isBeingDragged: boolean;
};

const Calculator = lazy(() => import('./Calculator/Calculator'));
const VSCode = lazy(() => import('./VSCode/VSCode'));
const Calendar = lazy(() => import('./Calendar/Calendar'));

const PlaceholderApp = lazy(() => import('./Placeholder/Placeholder'));

export const AppNexus = ({ appID, isBeingDragged }: AppNexusProps) => {
  if (appID === 'calculator') return <Calculator />;
  if (appID === 'vscode') return <VSCode isBeingDragged={isBeingDragged} />;
  if (appID === 'calendar') return <Calendar />;

  return <PlaceholderApp appID={appID} />;
};
