// src/components/Desktop/Window/WindowsArea.svelte
<script lang="ts">
  import { appsConfig } from '__/configs/apps/apps-config';
  import { activeApp, activeAppZIndex, openApps } from '__/stores/apps.store';

  $: $activeApp, ($activeAppZIndex += 2);
</script>

<section>
  {#each Object.keys(appsConfig) as appID}
    {#if $openApps[appID] && appsConfig[appID].shouldOpenWindow}
      {#await import('./Window.svelte') then { default: Window }}
        <Window {appID} />
      {/await}
    {/if}
  {/each}
</section>

<style lang="scss">
  section {
    display: block;

    position: fixed;

    // 1.7 rem is the heigh of the header
    // 5.25 rem is the height of dock
    top: 1.7rem;
    height: calc(100vh - 5.25rem - 1.7rem);

    width: 100vw;

    justify-self: center;
  }
</style>

// src/components/Desktop/Window/WindowsArea.tsx
import { useAtom } from 'jotai';
import { lazy } from 'preact/compat';
import { useEffect } from 'preact/hooks';
import { Suspense } from 'react';
import { appsConfig } from '__/data/apps/apps-config';
import { activeAppStore, activeAppZIndexStore, openAppsStore } from '__/stores/apps.store';
import css from './WindowsArea.module.scss';

const Window = lazy(() => import('./Window'));

export const WindowsArea = () => {
  const [openApps] = useAtom(openAppsStore);
  const [activeApp] = useAtom(activeAppStore);
  const [activeAppZIndex, setActiveAppZIndex] = useAtom(activeAppZIndexStore);

  // Update the active app Z Index here
  useEffect(() => {
    setActiveAppZIndex(activeAppZIndex + 2);
  }, [activeApp]);

  return (
    <section class={css.container}>
      <Suspense fallback={<span></span>}>
        {Object.keys(appsConfig).map(
          (appID) =>
            openApps[appID] &&
            appsConfig[appID].shouldOpenWindow && <Window key={appID} appID={appID} />,
        )}
      </Suspense>
    </section>
  );
};
